config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  # get '/books', to: 'books#index'
  delete '/reviews/:id', to: 'reviews#destroy', as: 'review'

  delete '/authors/:id', to: 'authors#destroy'
  get '/authors/:id', to: 'authors#show', as: 'author'

  post '/users', to: 'users#create', as: 'users'
  get  '/users/:id', to: 'users#show', as: 'user'
  get '/users/new', to: 'users#new', as: 'new_user'

  get '/books/:book_id/reviews/new', to: 'reviews#new', as: 'new_book_review'
  post '/books/:book_id/reviews', to: 'reviews#create', as: 'book_reviews'

  get '/books', to: 'books#index', as: 'books'
  post '/books', to: 'books#create'
  get '/books/new', to: 'books#new', as: 'new_book'
  get '/books/:id', to: 'books#show', as: 'book'
  delete '/books/:id', to: 'books#destroy'
# Mod 2 routes written as resources:
  # resources :books, :only => [:index, :show, :new, :create, :destroy] do
  #   resources :reviews, :only => [:new, :create]
  # end
  # resources :reviews, :only => [:destroy]
  # resources :authors, :only => [:show, :destroy]
  # resources :users, :only => [:new, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors
  validates :name, uniqueness: true, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  has_many :authors, through: :book_authors
  validates :title, uniqueness: true, presence: true
  validates_presence_of :pages, :year

  def avg_rating
    reviews.average(:rating).to_f.round(1)
  end

  def reviews_count
    reviews.size
  end

  def sort_reviews(direction)
    reviews.order("rating #{direction}")
  end

  def self.sort_reviews_number(direction)
    Book.arrange("reviews_count", "#{direction}")
  end

  def self.num_pages_sort(direction)
    Book.order("pages #{direction}")
  end

  def top_3_reviews
    sort_reviews('DESC').first(3)
  end

  def bottom_3_reviews
    sort_reviews('ASC').first(3)
  end

  def self.highest_rated_3
    Book.arrange('avg_rating', 'DESC').first(3)
  end

  def self.lowest_rated_3
    Book.arrange('avg_rating', 'ASC').first(3)
  end

  def self.highest_rated_average(direction)
    Book.arrange("avg_rating", "#{direction}")
  end

  def self.arrange(column, direction)
    Book.select('books.*, avg(rating) as avg_rating, count(reviews) as reviews_count')
    .joins(:reviews)
    .group(:book_id, :id)
    .order("#{column} #{direction}")
  end

  def multiple_authors(id)
    authors.where.not(id: id)
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to  :book, dependent: :destroy
  belongs_to  :author
end

app/models/review.rb
class Review < ApplicationRecord
  validates_presence_of :title, :description, :rating

  validates :rating, numericality: { less_than_or_equal_to: 5, greater_than_or_equal_to: 1, only_integer: true}

  belongs_to  :book
  belongs_to  :user

  def self.newest
    Review.order("created_at DESC")
  end

  def self.oldest
    Review.order("created_at ASC")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :books, through: :reviews
  validates :name, uniqueness: true, presence: true

  def self.top_3_reviewers

    User.most_reviews.first(3)
  end

  def self.most_reviews
    User.select('users.*, count(reviews) as reviews_count').joins(:reviews).group(:user_id, :id).order('reviews_count DESC')
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    books = @author.books
    books.each do |book|
      book.destroy
      end
    @author.destroy
    redirect_to books_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @users = User.all

    if params[:sort] == "avg_rating_ASC"
      @books = @books.highest_rated_average('ASC')
    elsif params[:sort] == "avg_rating_DESC"
      @books = @books.highest_rated_average('DESC')
    elsif params[:sort] == "num_pages_ASC"
      @books = @books.num_pages_sort('ASC')
    elsif params[:sort] == "num_pages_DESC"
      @books = @books.num_pages_sort('DESC')
    elsif params[:sort] == "num_reviews_ASC"
      @books = @books.sort_reviews_number('ASC')
    elsif params[:sort] == "num_reviews_DESC"
      @books = @books.sort_reviews_number('DESC')
    end

  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    bp = book_params
    bp[:title] = bp[:title].titlecase
  
    authors = bp[:authors].split(',')
    arr = []
    authors.each do |author|
      arr << Author.find_or_create_by(name: author.titlecase)
    end
    bp[:authors] = arr
    @book = Book.create(bp)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :pages, :year, :authors, :thumbnail)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def new
    @book = Book.find(params[:book_id])
    @review = Review.new()
  end

  def create
    rp = review_params
    @user = User.find_or_create_by(name: rp[:user])
    @book = Book.find(params[:book_id])
    @review = @book.reviews.create(user_id: @user.id, title: rp[:title], description: rp[:description], rating: rp[:rating].to_i)
    
    if @review.save
      redirect_to book_path(@review.book)
    else
      render :new
    end
  end

  def destroy
    review = Review.find(params[:id])
    @user = review.user
    review.destroy
    redirect_to user_path(@user.id)
  end

  private

  def review_params
    params.require(:review).permit(:user, :title, :description, :rating, :book_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @reviews = Review.where("user_id = ?", params[:id])
      if params[:sort] == "reviews_newest"
        @reviews = @reviews.newest
      elsif params[:sort] == "reviews_oldest"
        @reviews = @reviews.oldest
      end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/show.html.erb
<body class="show_page">
  <br>
  <br>
  <h2><%= @author.name %></h2>
  <br>
  <br>
  <br>
  <% @author.books.each do |book| %>
  <% if book.top_3_reviews.first %>
  <ul>
    <p>Author's highest rating: </p>
    <li><%= "Review Title: #{book.top_3_reviews.first.title}" %></li>
    <li><%= "Rating: #{book.top_3_reviews.first.rating}" %></li>
    <li>Reviewer: <%= link_to "#{book.top_3_reviews.first.user.name}", user_path(book.top_3_reviews.first.user_id) %></li>
  </ul>
  <% end %>
  <ul>
    <li><%= link_to "#{book.title}", book_path(book) %></li>
    <br>
    <li><%= "Year published: #{book.year }"%></li>
    <br>
    <li><%= "Number of pages: #{book.pages}" %></li>
    <% if book.multiple_authors(@author.id).count > 0 %>
    <% book.multiple_authors(@author.id).each do |co_author| %>

    <p>Co-author: <%= link_to "#{co_author.name}", author_path(co_author) %></p>
    <% end %>

    <% end %>
  </ul>
  <% end %>


  <%= link_to "Delete Author", author_path(@author), method: :delete %>
  <br>
</body>

app/views/books/index.html.erb
<div class="collection">
  <br>
  <h1>* The Collection *</h1>
  <br>
  <div id="stats">
    <h2 class="ui centered header">Statistics</h2>
    <div class="ui centered grid">
        <div class="ui five wide column">
          <div class="ui huge centered header">
            <p>Highest Rated Books: </p>
          </div>
          <div class="ui ordered list">
            <% @books.highest_rated_3.each do |book| %>
            <div class="item"><%= link_to "#{book.title}", book_path(book)%><%=", Rating: #{book.avg_rating}" %></div>
            <% end %>
          </div>
        </div>
        <div class="five wide column">
          <div class="ui huge centered header">
            <p>Lowest Rated Books: </p>
          </div>
          <div class="ui ordered list">
            <% @books.lowest_rated_3.each do |book| %>
              <div class="item"><%= link_to "#{book.title}", book_path(book)%><%=", Rating: #{book.avg_rating}" %></div>
            <% end %>
          </div>
        </div>
        <div class="five wide column">
          <div class="ui huge header">
            <p>Top Reviewers: </p>
          </div>
          <div class="ui ordered list">
              <% @users.top_3_reviewers.each do |user| %>
                <div class="item"><%= link_to "Username: #{user.name}", user_path(user)%><%=", Total number of reviews: #{user.reviews.count}"  %></div>
              <% end %>
          </div>
        </div>
      </div>
    <br>
    <br>
    <br>
    <br>
    </div>
  </div>
<div id="card-body" class="ui five centered cards">
    <% @books.each do |book| %>
    <div class="card-columns card">
      <div class="header">
        <h2><%= link_to "#{book.title}", book_path(book)%></h2>
      </div>
      <div class="image">
        <img class="medium rounded image" src="<%= book.thumbnail %>" alt="picture of book">
      </div>
      <div class="content">
        <div class="meta">
          <% book.authors.each do |author| %>
          <h3><%= link_to "#{author.name}", author_path(author) %></h3>
          <% end %>
        </div>
      </div>
      <div class="description">
        <p>Year: <%= book.year %></p>
        <p>Pages: <%= book.pages %></p>
        <p>Total Reviews: <%= book.reviews_count %></p>
        <p>Average Rating: <%= book.avg_rating %></p>
      </div>
    </div>
    <% end %>
  </div>

  <div id= "add_link" class="ui inverted brown eight item menu"><%= link_to 'Add New Book', new_book_path %></div>

app/views/books/new.html.erb
<html>
<body class="show_page">
<%= form_for @book do |f| %>
<% if @book.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
   <ul>
   <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
   </ul>
 </div>
<% end %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :pages%>
<%= f.number_field :pages %>
<%= f.label :year%>
<%= f.number_field :year %>
<%= f.label :authors %>
<%= f.text_field :authors, value: "" %>
<p>Please input your favorite book's image; our default link is below: </p>
<%= f.label :thumbnail %>
<%= f.text_field :thumbnail %>
<%= f.submit %>
<% end %>
</body>
</html>

app/views/books/show.html.erb
<html>
<body class="show_page">
<div class="show_page">

  <h1><%= @book.title %></h1>
  <% @book.authors.each do |author| %>
  <h1><%= link_to "Author: #{author.name}", author_path(author) %></h1>
  <% end %>
  <p>pages: <%= @book.pages %></p>
  <div class="stats">
    <h5>Top Reviews</h5>
    <% @book.top_3_reviews.each do |review| %>
    <ul>

      <%= link_to "#{review.user.name}", user_path(review.user) %>
      <%= review.title %>
      <%= "Rating: #{review.rating}" %>
      <br>
    </ul>
    <% end %>
    <br>
    <br>
    <h5>Worst Reviews</h5>
    <% @book.bottom_3_reviews.each do |review| %>
    <ul>

      <%= link_to "#{review.user.name}", user_path(review.user) %>
      <%= review.title %>
      <%= "Rating: #{review.rating}" %>
      <br>
    </ul>
    <% end %>
    <br>
    <br>
    <h5>Overall Average Rating</h5>
    <%= "#{@book.avg_rating} out of 5.0 possible" %>
    <br>
    <br>
  </div>
  <%= link_to 'Add New Review', new_book_review_path(@book.id) %>
  <br>
<br>
  <div id="all-reviews">

  <h2>All Book Reviews: </h2>
  <% @book.reviews.each do |review| %>
  <ul>
    <li><%= link_to review.user.name, user_path(review.user) %></li>
    <br>
    <li><%= "Review Title: #{review.title}" %></li>
    <br>
    <li><%= "Rating: #{review.rating} out of 5" %></li>
    <br>
    <li><%= "Review: #{review.description}" %></li>
  </ul>
  <% end %>
  <%= link_to "Delete Book", book_path(@book), method: :delete %>
</div>

</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="/stylesheets/normalize.css" type="text/css" />
    <link rel="stylesheet" href="/stylesheets/main.css" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <script src='https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js'></script>
    <title>BookClub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="ui inverted brown eight item menu">
      <li class="item"><%= link_to "books", books_path %></li>
      <li class="item"><%= link_to "home", root_path %></li>
      <li class="item"><%= link_to "sort books by ascending rating", books_path(sort: "avg_rating_ASC") %></li>
      <li class="item"><%= link_to "sort books by descending rating", books_path(sort: "avg_rating_DESC") %></li>
      <li class="item"><%= link_to "sort books by pages ascending", books_path(sort: "num_pages_ASC") %></li>
      <li class="item"><%= link_to "sort books by pages descending", books_path(sort: "num_pages_DESC") %></li>
      <li class="item"><%= link_to "sort books by review total ascending", books_path(sort: "num_reviews_ASC") %></li>
      <li class="item"><%= link_to "sort books by review total descending", books_path(sort: "num_reviews_DESC") %></li>
    </div>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<body class="show_page">
<%= form_for [@book, @review] do |f| %>
<%= f.hidden_field :book_id, value: @book.id %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :user%>
<%= f.text_field :user %>
<br>
<br>
<p>Rating must be between 1 and 5:</p>
<%= f.label :rating%>
<%= f.number_field :rating %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.submit %>
<% end %>
</body>

app/views/users/show.html.erb
<body class="show_page">
  <h3><%= "Reviewer: #{@user.name}" %></h3>
  <div class="reviews_sort">
    <li class="item"><%= link_to "sort reviews newest first", user_path(@user, sort: "reviews_newest") %></li>
    <br>
    <li class="item"><%= link_to "sort reviews oldest first", user_path(@user, sort: "reviews_oldest") %></li>
  </div>
  <% @reviews.each do |review| %>
  <div id="card-body" class="ui card">

  <ul>
    <div class="header">
      <li><%= "Book Reviewed: #{review.book.title}" %></li>
    </div>
    <br>
    <li><%= "Review Title: #{review.title}" %></li>
    <br>
    <li><%= "Review: #{review.description}" %></li>
    <br>
    <li><%= "Rating: #{review.rating}" %></li>
    <br>
    <li>Created at: <%= review.created_at.strftime("%B %d, %Y") %></li>
    <br>
  </ul>
  <br>
  <div class="ui basic brown button">
  <%= link_to "Delete Review", review_path(review), method: :delete %>
  </div>

  <br>
</div>
  <% end %>
</body>

app/views/welcome/index.html.erb
<html>
<body class="welcome">
<div>

  <br>
  <h1> Welcome to Book Club </h1>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <div class="entrance">

  <h3><%= link_to "See all books", books_path %></h3>
  </div>
</div>
</body>
</html>